# Use the official Python image.
FROM python:3.10-slim

# Set the working directory.
WORKDIR /app

# Copy requirements and install.
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy the app.
COPY app.py .

# Run the app.
CMD ["python", "app.py"]
